spring:
  profiles:
    active: local
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

# local
---
spring:
  profiles: local
  datasource:
    data: classpath:data-h2.sql
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true  
    
# real
---
spring:
  profiles: real
  datasource:
    url: jdbc:mariadb://sksggg123-webserver-rds.csrq1r9scrhy.ap-northeast-2.rds.amazonaws.com:3306/sksggg123
    username: sksggg123
    password: qud37979!
    driver-class-name: org.mariadb.jdbc.Driver