#spring:
#  mail:
#    host: smtp.gmail.com
#    username: medicc900@gmail.com #클라우드캐시 계정은 도메인관리자(Ken?)가 보안설정해줘야 사용가능
#    password: 
#    port: 587
#    protocol: smtp
#    default-encoding: UTF-8
#    properties:
#      mail:
#        smtp:
#          auth: true
#          starttls:
#            enable: true
# Test
spring:
  profiles:
    active: local # 기본환경
    
    
